Gdd 2777 push to pypi
VITObelgium/terracatalogueclient pull request #7
Opened 2024-11-27 13:56 UTC by wschoors

Also push package to PyPI

2024-11-28 14:03 UTC, StijnCaerts requested changes

2024-11-28 14:03 UTC, StijnCaerts commented on tests/test_hrvpp.py
Changes to this file should not be necessary.

2024-12-02 15:53 UTC, wschoors commented on Jenkinsfile
> +  python_version = '3.9'
Fixed

2024-12-02 15:53 UTC, wschoors commented on tests/test_hrvpp.py
Changes removed

2024-12-02 16:02 UTC, merged